### ISSUE TITLE
DECISIONS. Help. Before Theraptrix takes over the world.

### ISSUE THREAD

**Issue by neha13kaul** [sksuzuki/How-to-Learn-to-Code-2018#19]
I'm using the following code for parsing but I get 6 extra characters in my 'control' sample than in my 'theraptrix' sample. So while I'm able to get the error rate for the theraptrix sample (by comparing to the reference), I'm not able to compare the control sample to the reference correctly. Any idea why this might happen? The output file I generate (commented) shows an extra >c1 at the start of the parsed control sample.

with open("control.fa") as infile, open("output_ctrl.txt", 'w') as outfile:
    for line in infile:
        if line.startswith(">"): continue
        #outfile.write(line.strip())
        ctrl += line.strip()

**Comment by Jessime** [comment]
All three of the fasta files are formatted the same, so if you can parse one you should be able to parse them all. Can you post your full script as a file attachment?

(also, love the title)

**Comment by neha13kaul** [comment]
Sorry it's taken me so long to reply. Been swamped with work.
I'm replying to the email. Hope this works.
I tried a couple of different things but couldn't get it to work.
Everything is in the attached .py file.

**Comment by neha13kaul** [comment]
`

`

**Comment by neha13kaul** [comment]
I don't know how to attach this file. When I try, I get a message that it can't attach the file type. What file type should I be looking to attach?

**Comment by jimmyc13** [comment]
I made a little simpler version of the code inputs to make sure everything I was doing makes sense. I already have the code to get the info out of the files. I'm having trouble getting the mutations per single sequence. The code below easily gets me the total mutations in a given set, but I don't have the data for a t-test because I can't get mutations per sequence. Therefore I don't have a dataset to get a stdev from. I could divide the total mutations by 50 to get the average mutations/sequence, but I don't think that helps me get a p-value either. Unless I'm not understanding how to do the t-test, which is also possible.

```python

ref1=['accct']
    control1= ['accct','accct','acgct']
    test1= ['accct','actct','acgct']
    control_mut = []
    total_nuc=[]
    #print(set(zip(control1,*ref1)))
    for sequence1 in (control1[0:3]):
        for nuc1,nuc2 in zip(sequence1,*ref1):
            total_nuc.append(nuc2)
            if nuc1 != nuc2:
                control_mut.append(nuc1)
    print(total_nuc)
    print(control_mut)
    print(len(control_mut))
    
    test_mut = []
    for sequence1 in (test1):
        for nuc1,nuc2 in zip(sequence1,*ref1):
            if nuc1 != nuc2:
                test_mut.append(nuc1)
```
